export const COMMON_FETCH_USER_BEGIN = 'COMMON_FETCH_USER_BEGIN';
export const COMMON_FETCH_USER_SUCCESS = 'COMMON_FETCH_USER_SUCCESS';
export const COMMON_FETCH_USER_FAILURE = 'COMMON_FETCH_USER_FAILURE';
export const COMMON_FETCH_USER_DISMISS_ERROR = 'COMMON_FETCH_USER_DISMISS_ERROR';
