export const DASHBOARD_FETCH_ANALYSIS_BEGIN = 'DASHBOARD_FETCH_ANALYSIS_BEGIN';
export const DASHBOARD_FETCH_ANALYSIS_SUCCESS = 'DASHBOARD_FETCH_ANALYSIS_SUCCESS';
export const DASHBOARD_FETCH_ANALYSIS_FAILURE = 'DASHBOARD_FETCH_ANALYSIS_FAILURE';
export const DASHBOARD_FETCH_ANALYSIS_DISMISS_ERROR = 'DASHBOARD_FETCH_ANALYSIS_DISMISS_ERROR';
